//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XdsRepository.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServices")]
    public interface WebServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:RegistryStoredQuery", ReplyAction="urn:ihe:iti:2007:RegistryStoredQueryResponse")]
        System.ServiceModel.Channels.Message RegistryStoredQuery(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:RegisterDocumentSet-b", ReplyAction="urn:ihe:iti:2007:RegisterDocumentSet-bResponse")]
        System.ServiceModel.Channels.Message RegisterDocumentSet(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2010:RegisterOnDemandDocumentEntry", ReplyAction="urn:ihe:iti:2010:RegisterOnDemandDocumentResponse")]
        System.ServiceModel.Channels.Message RegisterOnDemandDocumentEntry(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2010:UpdateDocumentSet", ReplyAction="urn:ihe:iti:2010:UpdateDocumentSetResponse")]
        System.ServiceModel.Channels.Message UpdateDocumentSet(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2010:DeleteDocumentSet", ReplyAction="urn:ihe:iti:2010:DeleteDocumentSetResponse")]
        System.ServiceModel.Channels.Message DeleteDocumentSet(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:ProvideAndRegisterDocumentSet-b", ReplyAction="urn:ihe:iti:2007:ProvideAndRegisterDocumentSet-bResponse")]
        System.ServiceModel.Channels.Message ProvideAndRegisterDocumentSet(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:RetrieveDocumentSet", ReplyAction="urn:ihe:iti:2007:RetrieveDocumentSetResponse")]
        System.ServiceModel.Channels.Message RetrieveDocumentSet(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:hl7-org:v3:PRPA_IN201309UV02", ReplyAction="urn:hl7-org:v3:PRPA_IN201310UV02")]
        System.ServiceModel.Channels.Message PRPA_IN201309UV02(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:hl7-org:v3:PRPA_IN201301UV02", ReplyAction="urn:hl7-org:v3:MCCI_IN000002UV01")]
        System.ServiceModel.Channels.Message PRPA_IN201301UV02(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:rad:2009:RetrieveImagingDocumentSet", ReplyAction="urn:ihe:iti:2007:RetrieveDocumentSetResponse")]
        System.ServiceModel.Channels.Message RetrieveImagingDocumentSet(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:CrossGatewayQuery", ReplyAction="urn:ihe:iti:2007:CrossGatewayQueryResponse")]
        System.ServiceModel.Channels.Message CrossGatewayQuery(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ihe:iti:2007:CrossGatewayRetrieve", ReplyAction="urn:ihe:iti:2007:CrossGatewayRetrieveResponse")]
        System.ServiceModel.Channels.Message CrossGatewayRetrieve(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/wsn/bw-2/NotificationProducer/SubscribeRequest", ReplyAction="http://docs.oasis-open.org/wsn/bw-2/NotificationProducer/SubscribeResponse")]
        System.ServiceModel.Channels.Message SubscriptionRequest(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/UnsubscribeRequest", ReplyAction="http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/UnsubscribeResponse")]
        System.ServiceModel.Channels.Message UnsubscriptionRequest(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://docs.oasis-open.org/wsn/bw-2/NotificationConsumer/Notify")]
        void NotifyRequest(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/wsn/bw2/PullPoint/CreatePullPointRequest", ReplyAction="http://docs.oasis-open.org/wsn/bw-2/PullPoint/CreatePullPointResponse")]
        System.ServiceModel.Channels.Message CreatePullPointRequest(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServicesChannel : XdsRepository.ServiceReference1.WebServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServicesClient : System.ServiceModel.ClientBase<XdsRepository.ServiceReference1.WebServices>, XdsRepository.ServiceReference1.WebServices {
        
        public WebServicesClient() {
        }
        
        public WebServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message RegistryStoredQuery(System.ServiceModel.Channels.Message request) {
            return base.Channel.RegistryStoredQuery(request);
        }
        
        public System.ServiceModel.Channels.Message RegisterDocumentSet(System.ServiceModel.Channels.Message request) {
            return base.Channel.RegisterDocumentSet(request);
        }
        
        public System.ServiceModel.Channels.Message RegisterOnDemandDocumentEntry(System.ServiceModel.Channels.Message request) {
            return base.Channel.RegisterOnDemandDocumentEntry(request);
        }
        
        public System.ServiceModel.Channels.Message UpdateDocumentSet(System.ServiceModel.Channels.Message request) {
            return base.Channel.UpdateDocumentSet(request);
        }
        
        public System.ServiceModel.Channels.Message DeleteDocumentSet(System.ServiceModel.Channels.Message request) {
            return base.Channel.DeleteDocumentSet(request);
        }
        
        public System.ServiceModel.Channels.Message ProvideAndRegisterDocumentSet(System.ServiceModel.Channels.Message request) {
            return base.Channel.ProvideAndRegisterDocumentSet(request);
        }
        
        public System.ServiceModel.Channels.Message RetrieveDocumentSet(System.ServiceModel.Channels.Message request) {
            return base.Channel.RetrieveDocumentSet(request);
        }
        
        public System.ServiceModel.Channels.Message PRPA_IN201309UV02(System.ServiceModel.Channels.Message request) {
            return base.Channel.PRPA_IN201309UV02(request);
        }
        
        public System.ServiceModel.Channels.Message PRPA_IN201301UV02(System.ServiceModel.Channels.Message request) {
            return base.Channel.PRPA_IN201301UV02(request);
        }
        
        public System.ServiceModel.Channels.Message RetrieveImagingDocumentSet(System.ServiceModel.Channels.Message request) {
            return base.Channel.RetrieveImagingDocumentSet(request);
        }
        
        public System.ServiceModel.Channels.Message CrossGatewayQuery(System.ServiceModel.Channels.Message request) {
            return base.Channel.CrossGatewayQuery(request);
        }
        
        public System.ServiceModel.Channels.Message CrossGatewayRetrieve(System.ServiceModel.Channels.Message request) {
            return base.Channel.CrossGatewayRetrieve(request);
        }
        
        public System.ServiceModel.Channels.Message SubscriptionRequest(System.ServiceModel.Channels.Message request) {
            return base.Channel.SubscriptionRequest(request);
        }
        
        public System.ServiceModel.Channels.Message UnsubscriptionRequest(System.ServiceModel.Channels.Message request) {
            return base.Channel.UnsubscriptionRequest(request);
        }
        
        public void NotifyRequest(System.ServiceModel.Channels.Message request) {
            base.Channel.NotifyRequest(request);
        }
        
        public System.ServiceModel.Channels.Message CreatePullPointRequest(System.ServiceModel.Channels.Message request) {
            return base.Channel.CreatePullPointRequest(request);
        }
    }
}
